appName: app
namespace: default
environmentName: Default

image:
  repository: nginx
  tag: latest
  port: 80

resources:
  Default:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

autoscaling:
  Default:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75

liveness:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readiness:
  httpGet:
    path: /ready
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

env:
  Default:

serviceAccount:
  Default:
    roleArn: ""

dnsInternal:
  Default:
    domain: 
    gateways:

deployment:
  gracefulShutdown:
    terminationGracePeriodSeconds: 30
