appName: app
namespace: default
environmentName: default

image:
  repository: nginx
  tag: latest
  port: 80

resources:
  default:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

autoscaling:
  default:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /hc
    port: http

readinessProbe:
  httpGet:
    path: /ready
    port: http

env:
  default:

serviceAccount:
  name: ""
  roleArn: ""
