appName: app
namespace: default
environmentName: Default
awsAccountAlias: Default # 'Sandbox', 'Production', 'PciProduction'

image:
  repository: nginx
  tag: latest
  port: 80

resources:
  Sandbox:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  Production:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 192Mi
  PciProduction:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 192Mi

autoscaling:
  Sandbox:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75
  Production:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 70
  PciProduction:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 70

liveness:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readiness: {}

env:
  Default:

serviceAccount:
  Default:
    roleArn: ""

dnsInternal:
  Sandbox:
    domain: snb-r1.55tech-internal.com
    gateways:
    - istio-gateway
  Production:
    domain: prd-r1.55tech-internal.com
    gateways:
    - istio-gateway
  PciProduction:
    domain: service-r1.55tech-internal.com
    gateways:
     - private-istio-gateway

deployment:
  gracefulShutdown:
    terminationGracePeriodSeconds: 30
