{{- $envName := include "app.envName" . -}}
{{- $envResources := include "app.envValue" (dict "Values" .Values "Key" "resources" "Env" $envName) | fromYaml -}}
{{- $envServiceAccount := include "app.envValue" (dict "Values" .Values "Key" "serviceAccount" "Env" $envName) | fromYaml -}}
{{- $envVars := (index .Values.env $envName | default (index .Values.env "default")) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{.Values.environmentName}}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      environment: {{ .Values.environmentName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        environment: {{ .Values.environmentName }}
    spec:
      {{- if $envServiceAccount.roleArn }}
      serviceAccountName: {{.Values.appName}}-{{.Values.environmentName }}-sa
      {{- end }}
      terminationGracePeriodSeconds: {{default 30 .Values.gracefulshutdown.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: {{ .Values.appName }}
            environment: {{ .Values.environmentName }}
      containers:
      - name: {{ .Values.appName }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        ports:
          - containerPort: {{.Values.image.port}}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "{{ .Values.environmentName }}"
          - name: APP_ENV
            value: "{{ .Values.environmentName }}"
          - name: NODE_ENV
            value: "{{ .Values.environmentName }}"
          {{- range $env := $envVars}}
          - name: {{ $env.name }}
            value: "{{ $env.value }}"
          {{- end }}
        {{- with .Values.liveness }}
        livenessProbe:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.readiness }}
        readinessProbe:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $envResources }}
        resources:
{{ toYaml . | indent 12 }}
        {{- end }}