{{- $envResources := include "app.envValue" (dict "Values" .Values "Key" "resources" "Env" .Values.awsAccountAlias) | fromYaml -}}
{{- $envServiceAccount := include "app.envValue" (dict "Values" .Values "Key" "serviceAccount" "Env" .Values.awsAccountAlias) | fromYaml -}}
{{- $envVars := (index .Values.env .Values.awsAccountAlias | default (index .Values.env "default")) -}}
{{- $envName := include "app.toLower" .Values.environmentName -}}
{{- $appName := include "app.toLower" .Values.appName -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-{{$envName}}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
      environment: {{ $envName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ $appName }}
        environment: {{ $envName }}
    spec:
      {{- if $envServiceAccount.roleArn }}
      serviceAccountName: {{$appName}}-{{$envName }}-sa
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.gracefulShutdown.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: {{ $appName }}
            environment: {{ $envName }}
      containers:
      - name: {{ $appName }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        ports:
          - containerPort: {{.Values.image.port}}
        envFrom:
          - configMapRef:
              name: {{ .Values.mapConfigMapToEnv.generalName }}
          - configMapRef:
              name: {{ .Values.mapConfigMapToEnv.awsAccountName }}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "{{ .Values.environmentName }}"
          - name: APP_ENV
            value: "{{ .Values.environmentName }}"
          - name: NODE_ENV
            value: "{{ .Values.environmentName }}"
          - name: SHARED__OtelConfig__ServiceName
            value: "{{ .Values.appName }}"
          {{- range $env := $envVars}}
          - name: {{ $env.name }}
            value: "{{ $env.value }}"
          {{- end }}
        {{- with .Values.liveness }}
        livenessProbe:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.readiness }}
        readinessProbe:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $envResources }}
        resources:
{{ toYaml . | indent 12 }}
        {{- end }}