
{{- $envName := include "app.envName" . -}}
{{- $appName := include "app.appName" . -}}
{{- $envHPA := include "app.envValue" (dict "Values" .Values "Key" "autoscaling" "Env" .Values.environmentName) | fromYaml -}}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $appName }}-{{$envName}}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $appName }}-{{$envName}}-deployment
  minReplicas: {{ $envHPA.minReplicas }}
  maxReplicas: {{ $envHPA.maxReplicas }}
  {{- if or $envHPA.targetCPUUtilizationPercentage $envHPA.targetMemoryUtilizationPercentage }}
  metrics:
    {{- if $envHPA.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $envHPA.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $envHPA.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $envHPA.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
