{{- $envName := .Values.environmentName | default "default" -}}
{{- $envHPA := (index .Values.autoscaling $envName | default .Values.autoscaling.default) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: {{ $envHPA.minReplicas }}
  maxReplicas: {{ $envHPA.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $envHPA.targetCPUUtilizationPercentage }}