{{- $envName := include "app.toLower" .Values.environmentName -}}
{{- $appName := include "app.toLower" .Values.appName -}}
{{- $envHPA := include "app.envValue" (dict "Values" .Values "Key" "autoscaling" "Env" .Values.environmentName) | fromYaml -}}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName }}-{{ $envName }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
      environment: {{ $envName }}
  minAvailable: {{ $envHPA.minReplicas }}
