{{- if .Values.serviceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Values.appName) .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.roleArn }}"
{{- end }}