{{- $envName := include "app.envName" . -}}
{{- $envServiceAccount := include "app.envValue" (dict "Values" .Values "Key" "serviceAccount" "Env" $envName) | fromYaml -}}

{{- if $envServiceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Values.appName) $envServiceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ $envServiceAccount.roleArn }}"
{{- end }}