{{- $envName := include "app.toLower" .Values.environmentName -}}
{{- $appName := include "app.toLower" .Values.appName -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appName }}
    environment: {{ $envName }}
  ports:
    - port: 80
      targetPort: {{.Values.image.port}}
