{{- $envName := include "app.toLower" .Values.environmentName -}}
{{- $appName := include "app.toLower" .Values.appName -}}
{{- $envServiceAccount := include "app.envValue" (dict "Values" .Values "Key" "serviceAccount" "Env" .Values.awsAccountId) | fromYaml -}}

{{- if $envServiceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{$appName}}-{{$envName}}-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ $envServiceAccount.roleArn }}"
{{- end }}