{{- $envName := .Values.environmentName | default "default" -}}
{{- $envServiceAccount := (index .Values.serviceAccount $envName | default .Values.serviceAccount.default) -}}

{{- if $envServiceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Values.appName) $envServiceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ $envServiceAccount.roleArn }}"
{{- end }}