{{- $envName := include "app.envName" . -}}
{{- $envInternal := include "app.envValue" (dict "Values" .Values "Key" "internal" "Env" $envName) | fromYaml -}}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-{{ .Values.namespace }}-{{.Values.environmentName}}-vs
  namespace: istio-system
spec:
  hosts:
  - {{ .Values.appName }}.{{ .Values.namespace }}.{{ $envInternal.domain }}
  gateways:
{{ toYaml $envInternal.gateways | indent 4 }}
  http:
  - route:
    - destination:
        host: {{ .Values.appName }}-{{.Values.environmentName}}-service.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 80